### ISSUE TITLE
How to use annotatons

### ISSUE THREAD

**Issue by ghost** [kjunhwa/notopenyet#1]
How to use annotation(.mat)

**Comment by kjunhwa** [comment]
Hello,
.mat files are MATLAB's file extension and can be read using MATLAB. 
If you do not have a MATLAB license, you can read .mat files using the scipy.io library.

**Comment by ghost** [comment]
I use scipy.io read .mat.


Can you explain the meaning of the information in it? For example, the last one is a border, so what is the corresponding border category?


0 :&nbsp; [[1]
&nbsp;[1]
&nbsp;[1]
&nbsp;[1]
&nbsp;[1]
&nbsp;[1]
&nbsp;[1]
&nbsp;[1]] (8, 1)
1 :&nbsp; [[2]
&nbsp;[3]
&nbsp;[3]
&nbsp;[3]
&nbsp;[3]
&nbsp;[3]
&nbsp;[3]
&nbsp;[3]] (8, 1)
2 :&nbsp; [[3]
&nbsp;[2]
&nbsp;[2]
&nbsp;[2]
&nbsp;[2]
&nbsp;[2]
&nbsp;[2]
&nbsp;[2]] (8, 1)
3 :&nbsp; [[array(['Moving'], dtype='<U6')]&nbsp; &nbsp;
&nbsp;[array(['Moving'], dtype='<U6')]&nbsp; &nbsp; &nbsp; &nbsp;&nbsp;
&nbsp;[array(['Moving'], dtype='<U6')]&nbsp; &nbsp; &nbsp; &nbsp;&nbsp;
&nbsp;[array(['Moving'], dtype='<U6')]&nbsp; &nbsp; &nbsp; &nbsp;&nbsp;
&nbsp;[array(['Moving'], dtype='<U6')]&nbsp; &nbsp; &nbsp; &nbsp;&nbsp;
&nbsp;[array(['Moving'], dtype='<U6')]&nbsp; &nbsp; &nbsp; &nbsp;&nbsp;
&nbsp;[array(['Moving'], dtype='<U6')]&nbsp; &nbsp; &nbsp; &nbsp;&nbsp;
&nbsp;[array(['Moving'], dtype='<U6')]] (8, 1)
4 :&nbsp; [[array(['Buoy'], dtype='<U4')]&nbsp; &nbsp; &nbsp;
&nbsp;[array(['Vessel/ship'], dtype='<U11')]
&nbsp;[array(['Vessel/ship'], dtype='<U11')]
&nbsp;[array(['Vessel/ship'], dtype='<U11')]
&nbsp;[array(['Vessel/ship'], dtype='<U11')]
&nbsp;[array(['Vessel/ship'], dtype='<U11')]
&nbsp;[array(['Vessel/ship'], dtype='<U11')]
&nbsp;[array(['Vessel/ship'], dtype='<U11')]] (8, 1)
5 :&nbsp; [[array(['Other'], dtype='<U5')]
&nbsp;[array(['Far'], dtype='<U3')]
&nbsp;[array(['Far'], dtype='<U3')]
&nbsp;[array(['Far'], dtype='<U3')]
&nbsp;[array(['Far'], dtype='<U3')]
&nbsp;[array(['Far'], dtype='<U3')]
&nbsp;[array(['Far'], dtype='<U3')]
&nbsp;[array(['Far'], dtype='<U3')]] (8, 1)
6 :&nbsp; [[ 630&nbsp; 518&nbsp; 139&nbsp; 158]
&nbsp;[ 120&nbsp; 317&nbsp; 422&nbsp; 173]
&nbsp;[ 805&nbsp; 372&nbsp; 345&nbsp; 137]
&nbsp;[ 498&nbsp; 374&nbsp; 204&nbsp; &nbsp;99]
&nbsp;[1560&nbsp; 367&nbsp; 361&nbsp; 199]
&nbsp;[1524&nbsp; 492&nbsp; &nbsp;79&nbsp; &nbsp;29]
&nbsp;[1356&nbsp; 496&nbsp; &nbsp;25&nbsp; &nbsp;14]
&nbsp;[1324&nbsp; 491&nbsp; &nbsp;31&nbsp; &nbsp;18]] (8, 4)





------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年4月8日(星期五) 上午9:56
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [kjunhwa/SMD-Plus] How to use annotatons (Issue #1)





 
Hello,
 .mat files are MATLAB's file extension and can be read using MATLAB.
 If you do not have a MATLAB license, you can read .mat files using the scipy.io library.

**Comment by kjunhwa** [comment]
Use ObjectType and BB for object detection. Class information is in ObjectType, and it appears as Vessel/ship in content.

**Comment by ghost** [comment]
The coordinates is (xmin,ymin, xmax, ymax) or (xcenter, ycenter,w, h)




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "kjunhwa/SMD-Plus"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年4月8日(星期五) 上午10:20
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [kjunhwa/SMD-Plus] How to use annotatons (Issue #1)





 
Use ObjectType and BB for object detection. Class information is in ObjectType, and it appears as Vessel/ship in content.

**Comment by ghost** [comment]
think u&nbsp;



---Original---
From: ***@***.***&gt;
Date: Fri, Apr 8, 2022 10:20 AM
To: ***@***.***&gt;;
Cc: "Xu ***@***.******@***.***&gt;;
Subject: Re: [kjunhwa/SMD-Plus] How to use annotatons (Issue #1)




 
Use ObjectType and BB for object detection. Class information is in ObjectType, and it appears as Vessel/ship in content.
