### ISSUE TITLE
Missing detection and classification results

### ISSUE THREAD

**Issue by joel-huang** [kjunhwa/notopenyet#2]
![image](https://user-images.githubusercontent.com/25588253/206375825-551acf63-dd75-4f74-9768-bfdddeb1374e.png)

Hi Junhwa, could you upload the inference detection results? The paper mentions it, but it's not available for download.

Thanks!

**Comment by kjunhwa** [comment]
Thank you for notice. I will upload the table of result in the paper as soon as possible.
