### ISSUE TITLE
infrared videos

### ISSUE THREAD

**Issue by TahereSaidi** [kjunhwa/notopenyet#3]
Hello
Thanks for sharing the dataset.
Are the infrared videos not in the zip file?
I downloaded but did not see this file.
thanks.

**Comment by kjunhwa** [comment]
Thanks for your inquiry. Our dataset includes only OnShore and OnBoard scenarios, without infrared videos. For video data, please refer to the original SMD dataset. We provide modified Ground Truths for OnShore and OnBoard only.

**Comment by TahereSaidi** [comment]
thank you.
